version: '3.1'
services:
  test-container:
    image: postgres:15.5-alpine
    container_name: test_container
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=test-db
      - POSTGRES_HOST_AUTH_METHOD=trust
